name: UI CI/CD pipeline

on:
 #https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#onworkflow_dispatchinputs
  workflow_dispatch: 
    inputs:
      browser:
       description: set browser name for test execution
       required: true
       default: safari
       type: choice
       options:
          - chrome
          - safari
          
  #push:
    # branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
       
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: set JDK version
        uses: actions/setup-java@v4
        with:
            distribution: 'temurin'
            java-version: 18
          
      - name: Show Java version with message
        run: |
          echo "Java version is:"
          java -version
          echo "current working directory"
          pwd
      - name: find chrome browser
        run: |
         echo "finding chrome executable in system"
         which chromedriver || echo "chrome not found"
         #chmod +x /usr/bin/chromedriver
         #cd /usr/bin
         ls
      - name: kill the chrome process
        run: pkill chrome | echo "task is not runnng"
      - name: build maven
        run: mvn clean test -Dbrowser=${{inputs.browser}}
      - name: upload the artifacts
        uses: actions/upload-artifacts@v4
        with:
          name: Test Reoprt
          path: ''
