name: firefox pipeline

on:
  workflow_dispatch: 
    inputs:
      browser:
       description: set browsername for test execution
       required: true
       default: chrome
       type: string
    
#    push:
    #  branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
       
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: set JDK version
        uses: actions/setup-java@v4
        with:
            distribution: 'temurin'
            java-version: 18
          
      - name: Show Java version with message
        run: |
          echo "Java version is:"
          java -version
          echo "current working directory"
          pwd
      - name: find chrome browser
        run: |
         echo "finding chrome executable in system"
         which chromedriver || echo "chrome not found"
         #chmod +x /usr/bin/chromedriver
         #cd /usr/bin
         ls
      
      - name: kill the chrome process
        run: pkill chrome | echo "task is not runnng"
      - name: build maven
        run: mvn clean test
