name: firefox pipeline

on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
       
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Show Java version with message
        run: |
          echo "Java version is:"
          java -version
          echo "current working directory"
          pwd
      - name: Find Firefox path
        run: |
          echo "🔍 Locating Firefox binary..."
          which firefox
          echo "Full path using readlink:"
          readlink -f $(which firefox)
      - name: build maven
        run: mvn clean
